#
# GitHub Actions for automated PROJ-data release
#
# Only run on tag
# Only release if distcheck succeeds
# Only release if the tag name is identical to the full version

# NOTES
#
# https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
#
# - name: Save state
# run: echo "{name}={value}" >> $GITHUB_STAT
#
# - name: Set output
# run: echo "{name}={value}" >> $GITHUB_OUTPUT

# https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
# GITHUB_REF_NAME

name: 'Release'

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+RC[0-9]+'

jobs:
  release:
    name: 'Release on Tag'
    runs-on: ubuntu-latest

    # Only run docbuild on central repo
    if: github.repository == 'kbevers/PROJ-data'
    steps:

    - name: 'Install'
      run: |
        pwd
        uname -a
        sudo -E apt-get -yq --no-install-suggests --no-install-recommends install cmake

    - name: 'Check Out'
      uses: actions/checkout@v4

    - name: 'Final release?'
      id: release_type
      run: |
        echo "final_release=false" >> $GITHUB_OUTPUT
        if [[ ${{ github.ref }} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "final_release=true" >> $GITHUB_OUTPUT
        fi


    - name: 'Bundle & Check Package'
      id: bundle
      run: |
        pwd
        set -e
        
        mkdir _build && cd _build
        cmake --version
        cmake ..
        cmake --build . --target dist
        
        extensions=".tar.gz .zip"
        for ext in $extensions
        do
            for filename in $(ls *$ext)
            do
                `md5sum $filename > $filename.md5`
                `sha256sum $filename > $filename.sha256sum`
                `sha512sum $filename > $filename.sha512sum`
            done
        done

    - name: Create Pre-Release
      if: ${{ !steps.release_type.outputs.final_release }}
      id: create_prerelease
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        draft: true
        name: PROJ-data ${{ github.ref_name }}
        prerelease: true
        files: |
          ./_build/proj-data-*

    - name: Create Release
      if: ${{ steps.release_type.outputs.final_release }}
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        generate_release_notes: true
        draft: true
        name: PROJ-data ${{ github.ref_name }}
        prerelease: false
        files: |
          ./_build/proj-data-*
    